spring: 
  application:
    name: Config-Default
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
ribbon:
  eureka:
    enabled: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  OkToRetryOnAllOperations: true
  ReadTimeout: 5000
  ConnectTimeout: 3000
